### ISSUE TITLE
[Installation][eauth] Seeder fails

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/micro-PKC#21]
requires to manually run 
```
seed_status=$(sudo docker exec -it micro-pkc_eauth_1 sh -c 'npx sequelize-cli db:seed:all && echo "passYAY" || echo "fail"')
```
again to fix it. The seeder seems not to auto-run again after failing to connect to the DB.

docker logs e69ad1c2b5cd

$ node -r dotenv/config index.js 
Listening on port 8089
(node:29) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 172.19.0.2:3306
    at Promise.tap.then.catch.err (/usr/src/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:123:19)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 172.19.0.2:3306
    at Promise.tap.then.catch.err (/usr/src/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:123:19)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
yarn run v1.22.4

**Comment by FantasticoFox** [comment]
![image](https://user-images.githubusercontent.com/45313235/135203331-9675426a-78d6-4435-af94-65c44e8071f6.png)

Problem persists on amazon micro instances.

sudo docker logs micro-pkc_eauth_1
yarn run v1.22.4
$ node -r dotenv/config index.js 
Listening on port 8089
(node:30) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 172.19.0.2:3306
    at Promise.tap.then.catch.err (/usr/src/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:123:19)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:30) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 172.19.0.2:3306
    at Promise.tap.then.catch.err (/usr/src/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:123:19)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
yarn run v1.22.4
$ node -r dotenv/config index.js 
Listening on port 8089
Executing (default): CREATE TABLE IF NOT EXISTS `user` (`id` INTEGER(11) NOT NULL auto_increment UNIQUE , `address` VARCHAR(42), `scope` VARCHAR(255), PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): CREATE TABLE IF NOT EXISTS `oauth_clients` (`id` INTEGER(14) NOT NULL auto_increment UNIQUE , `name` VARCHAR(255), `client_id` VARCHAR(80), `client_secret` VARCHAR(80), `redirect_uri` VARCHAR(2000), `grant_types` VARCHAR(80), `scope` VARCHAR(255), `user_id` INTEGER(11), PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
(node:30) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: Can't create table `eauth`.`oauth_clients` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Query.formatError (/usr/src/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Query.handler [as onResult] (/usr/src/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Query.execute (/usr/src/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/usr/src/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/usr/src/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/usr/src/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/usr/src/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FantasticoFox** [comment]
We wait for pelith to finish the next update where we expect this problem to be solved (push to dockerhub).

**Comment by FantasticoFox** [comment]
Seeder is not run in EAUTH setup anymore. Fixed.
